export const LOADER = "UPDATE_LOADER";
export const ERROR = "UPDATE_ERROR";
export const SEARCHPARAMS = "UPDATE_SEARCHPARAMS";
export const MODAL = "UPDATE_MODAL";

export const SEARCH_RESULT = "UPDATE_SEARCH_RESULT";
export const SEARCH_RESULT_CATEGORY = "SEARCH_RESULT_CATEGORY"
export const SEARCH_BUSES = "UPDATE_SEARCH_BUSES";
export const SORT_BUSES = "UPDATE_SORT_BUSES";
export const FILTER = "UPDATE_FILTER";
export const STATIC_FILTER = "UPDATE_STATIC_FILTER";

export const SEATCHART = "UPDATE_SEATCHART";
export const SEL_SEATS = "UPDATE_SEL_SEATS";
export const SEL_INFO = "UPDATE_SEL_INFO";

export const UPDATE_RESULT = "UPDATE_RESULT";
export const UPDATE_CAMPAIGN_LIST = "UPDATE_CAMPAIGNS_LIST";


export const ACTION_ON_CAMPAIGN = "ACTION_ON_CAMPAIGN";
export const UPDATE_CAMPAIGN_INFO = "GET_CAMPAIGN_INFO";
export const ADD_CAMPAIGN = "ADD_CAMPAIGN"; 

export const UPDATE_CAMPAIGN = "UPDATE_CAMPAIGN";

